version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
        - "dependencies"
        - "github_actions"
        - "chore"
        - "bump-patch"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
        - "dependencies"
        - "javascript"
        - "chore"
        - "bump-patch"
